# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-09 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20180309_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
